/** Catalogue marque → modèles (top marché français). Non exhaustif :
 *  l'utilisateur peut toujours sélectionner "Autre" et saisir manuellement. */
export const CAR_CATALOG: Record<string, string[]> = {
  Renault: ["Clio", "Captur", "Megane", "Scenic", "Kadjar", "Kangoo", "Twingo", "Talisman", "Zoe", "Arkana", "Austral", "Espace", "Master", "Trafic", "Koleos"],
  Peugeot: ["108", "208", "308", "408", "508", "2008", "3008", "5008", "Partner", "Rifter", "Expert", "Boxer", "Traveller", "RCZ", "iOn"],
  Citroën: ["C1", "C3", "C3 Aircross", "C4", "C4 X", "C5 X", "C5 Aircross", "Berlingo", "Spacetourer", "Jumper", "Jumpy", "Picasso", "ë-C4"],
  DS: ["DS3", "DS3 Crossback", "DS4", "DS5", "DS7 Crossback", "DS9"],
  Volkswagen: ["Polo", "Golf", "ID.3", "ID.4", "ID.5", "ID.Buzz", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Passat", "Arteon", "Sharan", "Touran", "Caddy", "Transporter", "Crafter", "Up!"],
  Mercedes: ["Classe A", "Classe B", "Classe C", "Classe E", "Classe S", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "EQA", "EQB", "EQC", "EQE", "EQS", "Vito", "Sprinter", "Classe V"],
  BMW: ["Série 1", "Série 2", "Série 3", "Série 4", "Série 5", "Série 6", "Série 7", "Série 8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "i3", "i4", "iX", "iX3", "Z4"],
  Audi: ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "e-tron", "TT", "R8", "RS"],
  Toyota: ["Aygo", "Aygo X", "Yaris", "Yaris Cross", "Corolla", "Camry", "RAV4", "C-HR", "Highlander", "Land Cruiser", "Prius", "Proace", "Hilux", "Mirai", "bZ4X"],
  Ford: ["Fiesta", "Focus", "Mondeo", "Puma", "Kuga", "EcoSport", "Edge", "Mustang", "Mustang Mach-E", "Ranger", "Transit", "Tourneo", "Galaxy"],
  Hyundai: ["i10", "i20", "i30", "Kona", "Tucson", "Santa Fe", "IONIQ 5", "IONIQ 6", "Bayon", "Nexo", "Staria"],
  Kia: ["Picanto", "Rio", "Ceed", "ProCeed", "XCeed", "Stonic", "Niro", "Sportage", "Sorento", "EV6", "EV9", "Soul", "Stinger"],
  Skoda: ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Citigo"],
  Seat: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Mii"],
  Cupra: ["Born", "Formentor", "Leon", "Ateca", "Tavascan"],
  Nissan: ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "Note", "Navara", "Townstar", "Primastar"],
  Opel: ["Corsa", "Astra", "Mokka", "Crossland", "Grandland", "Combo", "Vivaro", "Movano", "Insignia", "Karl", "Adam"],
  Fiat: ["500", "500X", "500L", "Panda", "Tipo", "Punto", "Doblò", "Ducato", "Talento", "600", "Topolino"],
  Dacia: ["Sandero", "Logan", "Duster", "Jogger", "Spring", "Dokker", "Lodgy"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  Volvo: ["XC40", "XC60", "XC90", "S60", "S90", "V60", "V90", "EX30", "EX90", "C40", "EC40"],
  MINI: ["Cooper", "Cooper S", "One", "Countryman", "Clubman", "Paceman", "Electric", "Cabrio"],
  Mazda: ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "MX-30"],
  Honda: ["Jazz", "Civic", "HR-V", "CR-V", "e:Ny1", "e"],
  Suzuki: ["Swift", "Vitara", "S-Cross", "Ignis", "Jimny", "Across", "SX4"],
  Jeep: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Avenger"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Freelander"],
  Porsche: ["911", "718", "Cayman", "Boxster", "Macan", "Cayenne", "Panamera", "Taycan"],
  Lexus: ["CT", "IS", "ES", "LS", "UX", "NX", "RX", "GX", "LX", "RC", "LC", "RZ"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "Giulietta", "MiTo", "4C", "Brera"],
  BYD: ["Atto 3", "Han", "Seal", "Dolphin", "Tang", "Sealion", "Seal U"],
  Polestar: ["1", "2", "3", "4"],
  Smart: ["Fortwo", "Forfour", "#1", "#3"],
  Mitsubishi: ["ASX", "Outlander", "Eclipse Cross", "Space Star", "L200"],
  Subaru: ["Impreza", "Forester", "Outback", "XV", "BRZ", "Crosstrek", "Solterra"],
  Jaguar: ["F-Pace", "E-Pace", "I-Pace", "F-Type", "XE", "XF", "XJ"],
  MG: ["ZS", "MG4", "MG5", "Marvel R", "HS", "EHS", "Cyberster"],
};

export const BRAND_LIST = Object.keys(CAR_CATALOG).sort((a, b) => a.localeCompare(b, "fr"));
